name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: Frogobox ID

on:

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: |
          wget https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk18on/1.78.1/bcprov-jdk18on-1.78.1.jar

          sed -i 's/applicationId = "com.arn.scrobble"/applicationId = "com.github.futpib.panoscrobbler"/g' ./app/build.gradle.kts

          echo -n 999 > ./app/version.txt

          echo 'release.keystore=keystore.kjs' >> ./local.properties
          echo 'release.storePassword=keystore.kjs' >> ./local.properties
          echo 'release.alias=keystore.kjs' >> ./local.properties
          echo 'release.password=keystore.kjs' >> ./local.properties

          (
          echo keystore.kjs
          echo keystore.kjs
          yes
          ) | keytool -genkey -alias keystore.kjs -keyalg RSA -keystore ./app/keystore.kjs -keysize 2048

          yes | keytool -genkeypair -alias selfsigned -keyalg RSA -keysize 2048 -validity 3650 -keystore ./app/src/main/res/raw/embedded_server_bks.bks -storetype BKS -storepass EMBEDDED_SERVER_KEYSTORE_PASSWORD -keypass EMBEDDED_SERVER_KEYSTORE_PASSWORD -provider org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath ./bcprov-jdk18on-1.78.1.jar

          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 -di > ./app/src/google-services.json

          sha256sum \
            ./app/keystore.kjs \
            ./app/src/main/res/raw/embedded_server_bks.bks

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        continue-on-error: true
        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew genDict build

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      # Create Bundle AAB Release
      # Noted for main module build [main_project_module]:bundleRelease
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      # Noted For Output [main_project_module]/build/outputs/bundle/release/
      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
